apiVersion: v1
kind: Service
metadata:
  name: usermanagement-system-k8s-svc
spec:
  selector:
    app: usermanagement-system-k8s
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
  type: LoadBalancer
